version: '3.9'

networks:
  app-network-microservice:
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-member
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_tubes_member
    networks:
      app-network-microservice:
        aliases:
          - mysql-member
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-member
    networks:
      app-network-microservice:
        aliases:
          - redis-member

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-member
    environment:
      PMA_HOST: mysql-member
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - app-network-microservice

  service-member:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-member
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql-member
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db_tubes_member
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 12345
      REDIS_HOST: redis-member
      REDIS_PORT: 6379
      SERVER_PORT: 9001
    networks:
      - app-network-microservice
    restart: on-failure
