version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_tubes_member
    ports:
      - "3390:3306"
    networks:
      - app-network-microservice
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6390:6379"
    networks:
      - app-network-microservice

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network-microservice

  service-member:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-member
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db_tubes_member
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 12345
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 9001
    ports:
      - "9001:9001"
    networks:
      - app-network-microservice
    restart: on-failure

networks:
  app-network-microservice:
    external: true
